var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/dashboard/alerts/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__048b9e74._.js")
R.c("server/chunks/ssr/_6139f1ce._.js")
R.c("server/chunks/ssr/_b5ed35e2._.js")
R.c("server/chunks/ssr/[root-of-the-server]__5f98963d._.js")
R.c("server/chunks/ssr/[root-of-the-server]__a64655ed._.js")
R.c("server/chunks/ssr/node_modules_next_dist_70ed294b._.js")
R.c("server/chunks/ssr/app_b9b1292a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/app_layout_tsx_271801d7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/app_dashboard_layout_tsx_12b56d5a._.js")
R.c("server/chunks/ssr/_next-internal_server_app_dashboard_alerts_page_actions_8399cfd4.js")
R.m(68239)
module.exports=R.m(68239).exports
